[package]
name = "cphasing"
version = "0.0.15"
edition = "2021"

[[bin]]
name = "cphasing-rs"
path = "src/main.rs"

[profile.dev]
opt-level = 1
overflow-checks = false

[dependencies]
minimap2 = { path = "../minimap2-rs", features = ["default"]}
anyhow = "1.0.70"
bio = "*"
clap = { version = "4.4.10" }
chrono = { version = "0.4.24" }
crossbeam = "0.8.2"
crossbeam-channel = "0.5.8"
csv = { version = "1.1.6" }
flate2 = {version = "~1", default-features = false}
gzp = { version = "*" }
lazy_static = { version = "1.4.0" }
log = { version = "0.4.17" }
ndarray = { version = "0.15.6" }
no-panic = { version = "0.1" }
noodles = { version = "0.57.0", features = ["core", "fasta", "bed", "vcf"]}
nthash = { version = "0.5.1" }
env_logger = { version = "0.10.0" }
itertools = { version = "0.10.5"}
indexmap = { version = "2.1.0" }
ordered-float = { version = "4.0", default-features = false }
pathfinding = { version = "4.3.2" }
rand = { version = "0.8.5"}
rayon = { version = "1.8.0" }
regex = { version = "1.9" }
rust-lapper = { version = "1.1.0"}
rust-htslib = { version = "0.44.1", default-features = false }
# rust-seq2kminmers = { version = "0.1.0" }
serde = { version = "1.0", features = ["derive"]}
seq_io = { version = "0.4.0-alpha.0" }
tempfile = { version = "3.8.0" }
# tokio = { features = ["fs", "io-util"] }

[profile.release]
opt-level = 'z'
lto = true
