[package]
name = "cphasing"
version = "0.0.3"
edition = "2021"

[[bin]]
name = "cphasing-rs"
path = "src/main.rs"

[profile.dev]
opt-level = 1
overflow-checks = false

[dependencies]
anyhow = "1.0.70"
bio = "*"
clap = { version = "4.2.1" }
chrono = { version = "0.4.24" }
csv = { version = "1.1.6" }
flate2 = {version = "~1", default-features = false}
gzp = { version = "*" }
lazy_static = { version = "1.4.0" }
log = { version = "0.4.17" }
env_logger = { version = "0.10.0" }
ndarray = { version = "0.15.6" }
itertools = { version = "0.10.5"}
rand = { version = "0.8.5"}
rust-seq2kminmers = { version = "0.1.0" }
serde = { version = "1.0", features = ["derive"]}
seq_io = { version = "0.4.0-alpha.0" }