[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.2"
# CI backends to support
ci = "github"
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"

binaries-in-root = true
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-unknown-linux-musl", "x86_64-unknown-linux-musl"]
# Whether CI should trigger releases with dispatches instead of tag pushes
dispatch-releases = true
# Which phase dist should use to create the GitHub release
github-release = "announce"
# Whether to auto-include files like READMEs, LICENSEs, and CHANGELOGs (default true)
auto-includes = false
# The installers to generate for each app
installers = []
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["ci"]


[dist.github-custom-runners]
aarch64-unknown-linux-musl = "ubuntu-latest"
aarch64-unknown-linux-gnu = "ubuntu-latest"
x86_64-unknown-linux-musl = "ubuntu-latest"
x86_64-unknown-linux-gnu = "ubuntu-latest"
