[package]
name = "prune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4" }
csv = "1.1.6"
itertools = "0.10.5"
serde = { version = "1.0", features = ["derive"] }
